# EDITTED: Clean-up to resolve the dependancy issue (+ albumentataions for GFM: TerraMind)

name: zeroflood-eusar

channels:
  - conda-forge
  - pytorch
  - nvidia
channel_priority: strict

dependencies:
  # Core
  - python>=3.10
  - numpy
  - pillow
  - tqdm
  - tifffile

  # PyTorch
  - pytorch
  - torchvision
  - torchaudio
  # - pytorch-cuda=11.8

  # Geo / raster
  - geopandas
  - rasterio
  - rioxarray
  - zarr
  - cartopy

  # Vision / ML
  - albumentations
  - opencv
  - scikit-learn
  - timm
  - einops
  - tensorboard
  - diffusers

  # Utilities
  - gdown
  - ptflops
  - google-cloud-storage
  - omegaconf
  - pydataverse
  - pytest
  - yacs
  - wandb
  - hydra-core