_target_: pangaea.encoders.terramind_tim_encoder.terramind_v1_large_tim
encoder_weights: /home/vmarsocci/pangaea-bench/pretrained_models/TerraMind_v1_large.pt
download_url: null    # https://huggingface.co/ibm-esa-geospatial/TerraMind-1.0-large

input_size: 224
patch_size: 16
merge_method: null
modalities: ["S1RTC"]

input_bands:
  sar:
    - VV
    - VH

output_layers:
  - 5     
  - 11
  - 17    
  - 23

output_dim: 1024

# NOTE: ADDED for TiM -----------------------------------
tim_modalities: ['S2L2A', 'LULC', 'DEM']
pretrained: True
tim_chained_generations: False
# ------------------------------------------------------