_target_: pangaea.encoders.terramind_encoder.terramind_v1_base
encoder_weights: /home/vmarsocci/pangaea-bench/pretrained_models/TerraMind_v1_base.pt
download_url: null    # https://huggingface.co/ibm-esa-geospatial/TerraMind-1.0-base

input_size: 224
patch_size: 16
merge_method: null
modalities: ["S2L2A"]

input_bands:
  optical:
    - B1
    - B2
    - B3
    - B4
    - B5
    - B6
    - B7
    - B8
    - B8A
    - B9
    # - B10
    - B11
    - B12

output_layers:
  - 2     
  - 5
  - 8    
  - 11    

output_dim: 768